In [2]:
import numpy as np
import pymatgen
from pymatgen.ext.matproj import MPRester
import pandas as pd
from pymatgen.core import Structure, Composition  #import Structure and Composition classes from pymatgen.core
from pymatgen.io.cif import CifParser
import pandas as pd
import matminer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
#from sklearn.linear_model import LinearRegression
import matminer
from matminer.datasets import load_dataset

https://hackingmaterials.lbl.gov/matminer/dataset_summary.html

In [8]:
bnd_data=load_dataset("matbench_expt_gap")#expt bnd dataset

Fetching matbench_expt_gap.json.gz from https://ml.materialsproject.org/projects/matbench_expt_gap.json.gz to /home/scanmat/miniconda3/lib/python3.9/site-packages/matminer/datasets/matbench_expt_gap.json.gz

Fetching https://ml.materialsproject.org/projects/matbench_expt_gap.json.gz in MB: 0.038911999999999995MB [00:00,  2.18MB/s]

In [9]:
bnd_data

            composition  gap expt
0              Ag(AuS)2      0.00
1            Ag(W3Br7)2      0.00
2      Ag0.5Ge1Pb1.75S4      1.83
3     Ag0.5Ge1Pb1.75Se4      1.51
4                Ag2BBr      0.00
...                 ...       ...
4599             ZrTaN3      1.72
4600               ZrTe      0.00
4601             ZrTi2O      0.00
4602             ZrTiF6      0.00
4603               ZrW2      0.00

[4604 rows x 2 columns]

In [ ]:
flla_data = flla_data.dropna()

In [10]:
bnd_data=bnd_data.dropna()

In [6]:
flla_data=flla_data.drop(['material_id'],axis=1)

In [7]:
flla_data

,e_above_hull,formula,nsites,structure,formation_energy,formation_energy_per_atom
0,0.107405,{'As': 1.0},2,"[[1.11758409 0.79025129 1.93571242] As, [3.352...",0.214810,0.107405
1,0.000000,"{'S': 1.0, 'Hf': 2.0}",6,"[[0. 0. 8.84051822] S, [0. ...",-7.520110,-1.253352
2,0.000000,"{'P': 1.0, 'Mo': 3.0}",16,"[[1.62101142 2.03208456 2.71687137] P, [2.9549...",-5.429887,-0.339368
3,0.000000,"{'Al': 1.0, 'Si': 2.0, 'Co': 2.0}",5,"[[0. 0. 0.] Al, [-2.29850896e-08 2.26918935e+...",-2.684175,-0.536835
4,0.004781,{'Ga': 1.0},2,"[[2.39728273 0.77565449 2.62420188] Ga, [0.393...",0.009563,0.004781
...,...,...,...,...,...,...
3933,0.000000,"{'Si': 1.0, 'Nd': 1.0}",8,"[[0.98626121 5.20155909 4.42295358] Si, [2.958...",-6.112147,-0.764018
3934,0.000000,"{'Sc': 1.0, 'Si': 1.0}",4,"[[ 0.91698283 2.15720017 -0.00221565] Si, [2....",-3.345796,-0.836449
3935,0.000000,"{'Mn': 2.0, 'N': 1.0}",12,"[[2.19866151 3.62018922 0.74235726] N, [0. ...",-4.902647,-0.408554
3936,0.000000,"{'Nb': 2.0, 'C': 1.0, 'As': 1.0}",8,"[[0. 0. 6.03352716] C, [0. 0. ...",-4.901116,-0.612640
3937,0.000000,"{'B': 2.0, 'Ni': 1.0, 'Mo': 2.0}",5,"[[2.09378945 2.70715409 3.46713657] B, [1.7406...",-2.369551,-0.473910